name: publish to modrinth

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew remapJar
        env:
          TAG: ${{ github.event.release.tag_name }}

      - name: Upload a fabric build
        uses: actions/upload-artifact@v3
        with:
          path: build/libs/**.jar
          name: fabric
          retention-days: 2

  publish_fabric:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: fabric
          path: download

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: EjH4M3L1
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          loaders: |
            fabric
            quilt
          game-versions: |
            1.20.1
          modrinth-dependencies: |
            fabric-api | depends
          java: 17
          version: ${{ github.event.release.tag_name }}-fabric
          name: ${{ github.event.release.tag_name }}-fabric
          files: download/!(*-@(dev|dev-shadow)).jar